package cmd

import (
	"errors"
	"fmt"
	"io/ioutil"
	"os"

	yaml "gopkg.in/yaml.v2"

	"github.com/exitshell/konnect/engine"
	"github.com/exitshell/konnect/proxy"
	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

func getDefaultConfig() string {
	return "./konnect.yml"
}

// Remove duplicate elements from a string slice.
// https://goo.gl/ttDAg2
func removeDuplicates(elements []string) []string {
	encountered := map[string]bool{}
	result := []string{}
	for _, host := range elements {
		if encountered[host] == false {
			encountered[host] = true
			result = append(result, host)
		}
	}
	return result
}

// Resolve the config filename from cmd flags.
// Fallback to default filename.
// Validate that the file exists.
func resolveFilename(cmd *cobra.Command) (string, error) {
	// Get config filename from flags.
	filename, _ := cmd.Flags().GetString("filename")
	wasProvided := true

	// If filename is not specified, then set
	// to default config filename.
	if filename == "" {
		wasProvided = false
		filename = getDefaultConfig()
	}

	// Check if the filename exists.
	if _, err := os.Stat(filename); err != nil {
		// Could not find a config file.
		if wasProvided == false {
			err = errors.New("Could not find a " +
				"konnect.yml configuration file " +
				"in this directory")
		} else {
			// Could not find the config file that the user specified.
			err = fmt.Errorf("Config %v does not exist", filename)
		}
		return "", err
	}

	return filename, nil
}

func makeDefaultConfig(filename string) error {
	// Make default proxylist and konnect engine.
	proxyList := map[string]*proxy.SSHProxy{
		"app": &proxy.SSHProxy{
			User: "root",
			Host: "127.0.0.1",
			Port: 22,
			Key:  "/home/app/key",
		},
		"database": &proxy.SSHProxy{
			User: "admin",
			Host: "192.168.99.100",
			Port: 89,
			Key:  "~/.ssh/id_rsa",
		},
	}
	konnect := engine.New()
	konnect.Hosts = proxyList

	// Marshal konnect struct to a byte slice.
	byteSlice, err := yaml.Marshal(konnect)
	if err != nil {
		return err
	}

	// Make config header.
	header := []byte{}
	header = append(header, []byte(`# Autogenerated configuration file.`)...)
	header = append(header, 10)
	header = append(header, []byte(`# Define your hosts here and connect to them with konnect cli.`)...)
	header = append(header, 10, 10)

	// Make config body.
	data := []byte{}
	data = append(data, header...)
	data = append(data, byteSlice...)

	// Write byte slice to file.
	if err = ioutil.WriteFile(filename, data, 0644); err != nil {
		return err
	}

	fmt.Println("Created configuration file at:")
	c := color.New(color.FgCyan, color.Bold)
	c.Printf("%v\n", filename)

	return nil
}
